import { Octokit } from "octokit";
import Anthropic from "@anthropic-ai/sdk";
import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";
import { fetchActivitySince } from "./github.js";
import { generateStandup } from "./claude.js";
import { postToSlack } from "./slack.js";

type Period = "day" | "week" | "sprint";

const PERIOD_CONFIG: Record<Period, { ms: number; label: string }> = {
  day:    { ms: 24 * 60 * 60 * 1000,      label: "last 24 hours" },
  week:   { ms: 7 * 24 * 60 * 60 * 1000,  label: "last 7 days" },
  sprint: { ms: 14 * 24 * 60 * 60 * 1000, label: "last 2 weeks (sprint)" },
};

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }
  return value;
}

function formatDateRange(period: Period): string {
  const now = new Date();
  const today = now.toISOString().split("T")[0];

  if (period === "day") {
    return today;
  }

  const ms = PERIOD_CONFIG[period].ms;
  const start = new Date(now.getTime() - ms).toISOString().split("T")[0];
  return `${start} to ${today}`;
}

function markdownToHtml(markdown: string): string {
  return markdown
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`)
    .replace(/\n{2,}/g, "<br><br>")
    .replace(/\n/g, "\n");
}

function buildEmailHtml(summary: string, username: string, period: Period): string {
  const dateRange = formatDateRange(period);
  const periodLabel = PERIOD_CONFIG[period].label;
  const bodyHtml = markdownToHtml(summary);

  return `<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; line-height: 1.6; max-width: 600px; margin: 0 auto; padding: 20px; }
  h2 { color: #2d2d2d; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; margin-top: 0; }
  .meta { color: #666; font-size: 14px; margin-bottom: 20px; }
  ul { padding-left: 20px; }
  li { margin-bottom: 6px; }
  strong { color: #1a1a1a; }
  .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #e0e0e0; color: #999; font-size: 12px; }
</style>
</head>
<body>
  <h2>Standup Update</h2>
  <div class="meta">${username} &middot; ${periodLabel} &middot; ${dateRange}</div>
  ${bodyHtml}
  <div class="footer">Generated by Recap</div>
</body>
</html>`;
}

interface LambdaEvent {
  period?: string;
}

export async function handler(event: LambdaEvent = {}): Promise<{ statusCode: number; body: string }> {
  const periodKey = (event.period ?? "day") as Period;
  const config = PERIOD_CONFIG[periodKey];
  if (!config) {
    return { statusCode: 400, body: `Invalid period: "${event.period}". Must be one of: day, week, sprint` };
  }

  const githubToken = requireEnv("GITHUB_TOKEN");
  const anthropicKey = requireEnv("ANTHROPIC_API_KEY");
  const githubUsername = requireEnv("GITHUB_USERNAME");

  const octokit = new Octokit({ auth: githubToken });
  const anthropic = new Anthropic({ apiKey: anthropicKey });

  const since = new Date(Date.now() - config.ms).toISOString();
  const events = await fetchActivitySince(octokit, githubUsername, since);
  const standup = await generateStandup(anthropic, events, config.label);

  console.log(`Standup (${config.label}):\n`);
  console.log(standup.summary);

  // SES email delivery
  const sesRecipient = process.env.SES_RECIPIENT_EMAIL;
  const sesSender = process.env.SES_SENDER_EMAIL;
  if (sesRecipient && sesSender) {
    try {
      const dateRange = formatDateRange(periodKey);
      const subject = `Standup Update for ${githubUsername} | ${dateRange}`;
      const htmlBody = buildEmailHtml(standup.summary, githubUsername, periodKey);

      const ses = new SESClient({});
      await ses.send(new SendEmailCommand({
        Source: sesSender,
        Destination: { ToAddresses: [sesRecipient] },
        Message: {
          Subject: { Data: subject },
          Body: {
            Html: { Data: htmlBody },
            Text: { Data: standup.summary },
          },
        },
      }));
      console.log(`Standup emailed to ${sesRecipient}.`);
    } catch (err) {
      console.error("SES delivery failed:", err);
    }
  } else {
    console.log("SES_RECIPIENT_EMAIL or SES_SENDER_EMAIL not set, skipping email.");
  }

  // Slack delivery
  const slackWebhookUrl = process.env.SLACK_WEBHOOK_URL;
  if (slackWebhookUrl) {
    try {
      await postToSlack(slackWebhookUrl, standup, githubUsername, config.label);
      console.log("Standup posted to Slack.");
    } catch (err) {
      console.error("Slack delivery failed:", err);
    }
  } else {
    console.log("SLACK_WEBHOOK_URL not set, skipping Slack.");
  }

  return { statusCode: 200, body: standup.summary };
}
